#!/usr/bin/env python3
"""Render src/pkjs-template/index.js into src/pkjs/pebble-js-app.js with credentials.

The watchface fetches Claude and MiniMax directly from the phone, so the phone
needs its own copy of the Claude OAuth tokens and the MiniMax key. Reading them
here (rather than pasting them in by hand) keeps the secrets out of shell history
and out of any diff you might share.

    python tools/make_secrets.py     # then: pebble build && pebble install

Edit the template, never src/pkjs/pebble-js-app.js — the latter is overwritten on
every run. The secrets are inlined rather than kept in a second file the entry
point `require`s, because require() in pkjs needs enableMultiJS, which needs
webpack.

IMPORTANT: the generated file contains a live refresh token. It is listed in
.gitignore — do not commit it, and note that it ends up inside the installed .pbw
on your phone.

Claude's refresh token rotates on use: once the phone refreshes, the copy in
~/.claude/.credentials.json is dead and Claude Code on this machine will ask you
to log in again. Re-run this script after any such re-login to re-seed the phone.
"""

import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CREDENTIALS = Path.home() / ".claude" / ".credentials.json"
CONFIG = ROOT / "config.json"
TEMPLATE = ROOT / "src" / "pkjs-template" / "index.js"
# The name matters. Without "enableMultiJS": true in package.json, the SDK's
# process_js step only treats a file as the JS entry point if its path contains
# "pebble-js-app.js" — anything else is copied into the .pbw but never run, and
# the phone reports "No JS found". Enabling multiJS instead would pull in a
# webpack dependency for a single-file project.
OUT = ROOT / "src" / "pkjs" / "pebble-js-app.js"
PLACEHOLDER = "/*__SECRETS__*/{}"


def load_json(path, label):
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Pasted secrets sometimes carry a stray newline, illegal inside a JSON
        # string. Same tolerance the collector applies.
        try:
            return json.loads(re.sub(r"[\x00-\x1f]+", "", text))
        except json.JSONDecodeError as e:
            sys.exit(f"{label} is not valid JSON: {e}")


def main():
    oauth = load_json(CREDENTIALS, str(CREDENTIALS)).get("claudeAiOauth") or {}
    config = load_json(CONFIG, str(CONFIG))

    refresh = oauth.get("refreshToken") or ""
    access = oauth.get("accessToken") or ""
    expires = oauth.get("expiresAt") or 0

    if not refresh:
        print(f"warning: no claudeAiOauth.refreshToken in {CREDENTIALS} — "
              "the Claude rows will stay blank. Run Claude Code once, then re-run this.")
    minimax = config.get("minimax_key") or ""
    if not minimax:
        print(f"warning: no minimax_key in {CONFIG} — the MiniMax rows will stay blank.")

    payload = {
        "claudeRefreshToken": refresh,
        "claudeAccessToken": access,
        # milliseconds, as stored by Claude Code
        "claudeExpiresAt": expires,
        "minimaxKey": minimax,
        "minimaxUrl": config.get("minimax_url", ""),
        "minimaxModel": config.get("minimax_model", ""),
    }

    if not TEMPLATE.exists():
        sys.exit(f"missing template: {TEMPLATE}")
    template = TEMPLATE.read_text(encoding="utf-8")
    if PLACEHOLDER not in template:
        sys.exit(f"{TEMPLATE} no longer contains the {PLACEHOLDER} placeholder")

    rendered = template.replace(PLACEHOLDER, json.dumps(payload, indent=2), 1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by tools/make_secrets.py from src/pkjs-template/index.js.\n"
        "// Do not edit, do not commit — contains a live Claude refresh token and\n"
        f"// the MiniMax API key. Generated {time.strftime('%Y-%m-%d %H:%M:%S')}.\n"
        + rendered,
        encoding="utf-8",
    )

    def show(v):
        return f"{v[:12]}…({len(v)} chars)" if v else "(missing)"

    print(f"wrote {OUT}")
    print(f"  claude refresh token: {show(refresh)}")
    print(f"  claude access token:  {show(access)}", end="")
    if expires:
        left = int(expires / 1000 - time.time())
        print(f"  expires in {left // 60}m" if left > 0 else "  (already expired)")
    else:
        print()
    print(f"  minimax key:          {show(minimax)}")


if __name__ == "__main__":
    main()
