#!/usr/bin/env python3
"""Render the phone companion with configured service credentials.

Codex authenticates independently on the phone through device-code login;
Claude uses manual countdown calibration. The MiniMax key and optional GitHub
settings are baked into the generated companion.

    python tools/make_secrets.py     # then: pebble build && pebble install

Edit the template, never src/pkjs/pebble-js-app.js — the latter is overwritten on
every run. The secrets are inlined rather than kept in a second file the entry
point `require`s, because require() in pkjs needs enableMultiJS, which needs
webpack.

IMPORTANT: the generated file contains the live MiniMax API key. It is listed
in .gitignore — do not commit it, and note that it ends up inside the installed
.pbw on your phone.
"""

import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "config.json"
TEMPLATE = ROOT / "src" / "pkjs-template" / "index.js"
# The name matters. Without "enableMultiJS": true in package.json, the SDK's
# process_js step only treats a file as the JS entry point if its path contains
# "pebble-js-app.js" — anything else is copied into the .pbw but never run, and
# the phone reports "No JS found". Enabling multiJS instead would pull in a
# webpack dependency for a single-file project.
OUT = ROOT / "src" / "pkjs" / "pebble-js-app.js"
PLACEHOLDER = "/*__SECRETS__*/{}"


def load_json(path, label):
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        # Pasted secrets sometimes carry a stray newline, illegal inside a JSON
        # string. Same tolerance the collector applies.
        try:
            return json.loads(re.sub(r"[\x00-\x1f]+", "", text))
        except json.JSONDecodeError as e:
            sys.exit(f"{label} is not valid JSON: {e}")


def main():
    config = load_json(CONFIG, str(CONFIG))

    minimax = config.get("minimax_key") or ""
    if not minimax:
        print(f"warning: no minimax_key in {CONFIG} — the MiniMax rows will stay blank.")

    payload = {
        "minimaxKey": minimax,
        "minimaxUrl": config.get("minimax_url", ""),
        "minimaxModel": config.get("minimax_model", ""),
        "githubUsername": config.get("github_username", "LinBlink"),
        "githubToken": config.get("github_token", ""),
    }

    if not TEMPLATE.exists():
        sys.exit(f"missing template: {TEMPLATE}")
    template = TEMPLATE.read_text(encoding="utf-8")
    if PLACEHOLDER not in template:
        sys.exit(f"{TEMPLATE} no longer contains the {PLACEHOLDER} placeholder")

    rendered = template.replace(PLACEHOLDER, json.dumps(payload, indent=2), 1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by tools/make_secrets.py from src/pkjs-template/index.js.\n"
        "// Do not edit or commit — contains the live MiniMax API key.\n"
        f"// Generated {time.strftime('%Y-%m-%d %H:%M:%S')}.\n"
        + rendered,
        encoding="utf-8",
    )

    def show(v):
        return f"{v[:12]}…({len(v)} chars)" if v else "(missing)"

    print(f"wrote {OUT}")
    print(f"  minimax key:          {show(minimax)}")
    print(f"  github username:      {payload['githubUsername']}")
    print(f"  github token:         {show(payload['githubToken'])}")


if __name__ == "__main__":
    main()
